### ISSUE TITLE
文字列よりもシンボルの方が高速のためシンボル化する

### ISSUE THREAD

**Issue by norotime** [mem0112mem/wikiapp#24]
https://github.com/mem0112mem/wikiapp/blob/2e49cc305ed3bdf9f2b05300377f69bb406393fc/app/controllers/comments_controller.rb#L56

@mem0112mem 他にもないか全てチェックをお願いします。また、半角スペースを間に入れるなどして可読性を高めてください。細かいところにこそ、実力が見えてきてしまいます。

**Comment by mem0112mem** [comment]
・シンボル化する理由
文字列に比べてメモリ消費も少なく可読性もあがる
https://www.sejuku.net/blog/13094

**Comment by norotime** [comment]
他人のブログよりも、公式ドキュメントを読むようにしましょう。
Ruby リファレンス シンボル
で出てきますよー。

**Comment by mem0112mem** [comment]
ご指摘ありがとうございます。
https://docs.ruby-lang.org/ja/latest/class/Symbol.html
確認するようにします。

**Comment by norotime** [comment]
@mem0112mem はい！必ず！
